import type {
  EquipmentId,
  EquipmentLoadout,
  PartyMemberProgress,
  PartyMemberId,
} from "../types/game";

export interface EquipmentDefinition {
  id: EquipmentId;
  name: string;
  slot: keyof EquipmentLoadout;
  attack: number;
  defense: number;
  agility: number;
  description: string;
  price: number;
  allowedMembers: readonly PartyMemberId[];
}

export const CARBINE_EQUIPMENT_IDS = [
  "arc-carbine",
  "relay-carbine",
  "storm-carbine",
  "harbor-carbine",
  "cipher-carbine",
  "ion-carbine",
] as const satisfies readonly EquipmentId[];

export function isCarbineEquipment(equipmentId: EquipmentId | null): boolean {
  return equipmentId !== null && CARBINE_EQUIPMENT_IDS.includes(
    equipmentId as (typeof CARBINE_EQUIPMENT_IDS)[number],
  );
}

export const EQUIPMENT: Record<EquipmentId, EquipmentDefinition> = {
  "thunder-edge": { id:"thunder-edge",name:"THUNDER EDGE",slot:"weapon",attack:24,defense:2,agility:3,price:4200,allowedMembers:["ash"],description:"A grounding blade built for the weather station's emergency crews." },
  "ion-carbine": { id:"ion-carbine",name:"ION CARBINE",slot:"weapon",attack:33,defense:1,agility:7,price:4400,allowedMembers:["nox"],description:"An ionized rifle that remains accurate through charged air." },
  "tempest-disc": { id:"tempest-disc",name:"TEMPEST DISC",slot:"weapon",attack:25,defense:1,agility:10,price:4300,allowedMembers:["sera"],description:"A turbine-balanced disc that sweeps the enemy formation." },
  "pressure-mantle": { id:"pressure-mantle",name:"PRESSURE MANTLE",slot:"armor",attack:0,defense:17,agility:5,price:4500,allowedMembers:["ione","sera"],description:"Flexible pressure fibers that disperse impacts and electrical surges." },
  "aeroweave-mail": { id: "aeroweave-mail", name: "AEROWEAVE MAIL", slot: "armor", attack: 0, defense: 16, agility: 4, price: 3600, allowedMembers: ["ash","nox"], description: "Ceramic flight armor that protects without slowing its wearer." },
  "vector-core": { id: "vector-core", name: "VECTOR CORE", slot: "core", attack: 3, defense: 3, agility: 7, price: 3400, allowedMembers: ["ash","ione","nox","sera"], description: "An inertial stabilizer recovered from the launch service works." },
  "skyglass-guard": { id: "skyglass-guard", name: "SKYGLASS GUARD", slot: "shield", attack: 0, defense: 15, agility: 4, price: 3800, allowedMembers: ["ash","ione","nox","sera"], description: "A light flight-deck guard plate tuned to the atmospheric relay." },
  "cipher-carbine": { id: "cipher-carbine", name: "CIPHER CARBINE", slot: "weapon", attack: 28, defense: 1, agility: 6, price: 3100, allowedMembers: ["nox"], description: "An archive rifle that decodes shield carriers before firing." },
  "prism-lash": { id: "prism-lash", name: "PRISM LASH", slot: "weapon", attack: 17, defense: 1, agility: 6, price: 2950, allowedMembers: ["ione"], description: "A crystalline filament recovered from the sealed galleries." },
  "dawn-saber": { id: "dawn-saber", name: "DAWN SABER", slot: "weapon", attack: 20, defense: 2, agility: 2, price: 3000, allowedMembers: ["ash"], description: "A commander's blade that still holds the first evacuation signal." },
  "horizon-disc": { id: "horizon-disc", name: "HORIZON DISC", slot: "weapon", attack: 21, defense: 1, agility: 8, price: 3050, allowedMembers: ["sera"], description: "A returning disc calibrated for rapid multi-target strikes." },
  "aurora-mantle": { id: "aurora-mantle", name: "AURORA MANTLE", slot: "armor", attack: 0, defense: 12, agility: 4, price: 3200, allowedMembers: ["ione", "sera"], description: "Memory-fiber armor from the Custodian's command locker." },
  "relay-blade": {
    id: "relay-blade",
    name: "RELAY BLADE",
    slot: "weapon",
    attack: 3,
    defense: 0,
    agility: 0,
    description: "A short blade tuned to relay frequencies.",
    price: 18,
    allowedMembers: ["ash", "nox"],
  },
  "archive-rod": {
    id: "archive-rod",
    name: "ARCHIVE ROD",
    slot: "weapon",
    attack: 1,
    defense: 0,
    agility: 2,
    description: "A mnemonic conductor carried by Archive adepts.",
    price: 18,
    allowedMembers: ["ione"],
  },
  "pulse-saber": {
    id: "pulse-saber",
    name: "PULSE SABER",
    slot: "weapon",
    attack: 5,
    defense: 0,
    agility: 0,
    description: "A focused blade built in Lumen Hollow.",
    price: 42,
    allowedMembers: ["ash", "nox"],
  },
  "ion-whip": {
    id: "ion-whip",
    name: "ION WHIP",
    slot: "weapon",
    attack: 4,
    defense: 0,
    agility: 2,
    description: "A flexible conductor that rewards quick hands.",
    price: 56,
    allowedMembers: ["ione"],
  },
  "field-suit": {
    id: "field-suit",
    name: "FIELD SUIT",
    slot: "armor",
    attack: 0,
    defense: 2,
    agility: 0,
    description: "Light protection for unstable terrain.",
    price: 16,
    allowedMembers: ["ash", "nox"],
  },
  "woven-mantle": {
    id: "woven-mantle",
    name: "WOVEN MANTLE",
    slot: "armor",
    attack: 0,
    defense: 1,
    agility: 1,
    description: "Archive fibers that move before an impact lands.",
    price: 20,
    allowedMembers: ["ione"],
  },
  "guard-plate": {
    id: "guard-plate",
    name: "GUARD PLATE",
    slot: "armor",
    attack: 0,
    defense: 4,
    agility: -1,
    description: "Layered glass-metal armor for exposed routes.",
    price: 48,
    allowedMembers: ["ash", "nox"],
  },
  "signal-shield": {
    id: "signal-shield",
    name: "SIGNAL SHIELD",
    slot: "shield",
    attack: 0,
    defense: 3,
    agility: 0,
    description: "A defensive field folded into a wrist frame.",
    price: 36,
    allowedMembers: ["ash", "ione", "nox"],
  },
  "echo-core": {
    id: "echo-core",
    name: "ECHO CORE",
    slot: "core",
    attack: 2,
    defense: 2,
    agility: 0,
    description: "Amplifies the bearer through a remembered signal.",
    price: 0,
    allowedMembers: ["ash", "ione", "nox"],
  },
  "vault-edge": {
    id: "vault-edge",
    name: "VAULT EDGE",
    slot: "weapon",
    attack: 7,
    defense: 1,
    agility: 0,
    description: "A pre-collapse blade that resonates inside sealed structures.",
    price: 0,
    allowedMembers: ["ash"],
  },
  "phase-lash": {
    id: "phase-lash",
    name: "PHASE LASH",
    slot: "weapon",
    attack: 6,
    defense: 0,
    agility: 3,
    description: "A mnemonic filament that follows its wielder's intent.",
    price: 0,
    allowedMembers: ["ione"],
  },
  "vault-aegis": {
    id: "vault-aegis",
    name: "VAULT AEGIS",
    slot: "shield",
    attack: 0,
    defense: 5,
    agility: 1,
    description: "A compact barrier recovered from the Echo Vault core.",
    price: 0,
    allowedMembers: ["ash", "ione", "nox"],
  },
  "memory-prism": {
    id: "memory-prism",
    name: "MEMORY PRISM",
    slot: "core",
    attack: 3,
    defense: 3,
    agility: 2,
    description: "A rare prism still holding fragments of the Vault's memory.",
    price: 0,
    allowedMembers: ["ash", "ione", "nox"],
  },
  "starforged-saber": {
    id: "starforged-saber",
    name: "STARFORGED SABER",
    slot: "weapon",
    attack: 13,
    defense: 1,
    agility: 0,
    description: "A high-output blade forged for the southern storm roads.",
    price: 620,
    allowedMembers: ["ash"],
  },
  "resonance-lash": {
    id: "resonance-lash",
    name: "RESONANCE LASH",
    slot: "weapon",
    attack: 11,
    defense: 0,
    agility: 4,
    description: "A responsive mnemonic filament calibrated for Ione.",
    price: 680,
    allowedMembers: ["ione"],
  },
  "arc-carbine": {
    id: "arc-carbine",
    name: "ARC CARBINE",
    slot: "weapon",
    attack: 12,
    defense: 0,
    agility: 3,
    description: "A compact ranged weapon built for bridge scouts like Nox.",
    price: 760,
    allowedMembers: ["nox"],
  },
  "frontier-mail": {
    id: "frontier-mail",
    name: "FRONTIER MAIL",
    slot: "armor",
    attack: 0,
    defense: 10,
    agility: -1,
    description: "Heavy layered armor for pathfinders and bridge scouts.",
    price: 550,
    allowedMembers: ["ash", "nox"],
  },
  "phase-weave": {
    id: "phase-weave",
    name: "PHASE WEAVE",
    slot: "armor",
    attack: 0,
    defense: 9,
    agility: 3,
    description: "A light Archive weave that disperses delayed impacts.",
    price: 590,
    allowedMembers: ["ione"],
  },
  "storm-shield": {
    id: "storm-shield",
    name: "STORM SHIELD",
    slot: "shield",
    attack: 0,
    defense: 10,
    agility: 1,
    description: "A costly barrier tuned to the southern electrical fronts.",
    price: 720,
    allowedMembers: ["ash", "ione", "nox"],
  },
  "relay-carbine": {
    id: "relay-carbine",
    name: "RELAY CARBINE",
    slot: "weapon",
    attack: 15,
    defense: 0,
    agility: 5,
    description: "Synchronized relay coils give Nox a marked increase in power and response speed.",
    price: 0,
    allowedMembers: ["nox"],
  },
  "scout-coil": {
    id: "scout-coil",
    name: "SCOUT COIL",
    slot: "core",
    attack: 4,
    defense: 2,
    agility: 5,
    description: "A restored western relay coil that accelerates a scout's responses.",
    price: 0,
    allowedMembers: ["nox"],
  },
  "sun-edge": {
    id: "sun-edge",
    name: "SUN EDGE",
    slot: "weapon",
    attack: 14,
    defense: 2,
    agility: 1,
    description: "A command blade energized by the eastern tower's solar lattice.",
    price: 0,
    allowedMembers: ["ash"],
  },
  "oracle-loop": {
    id: "oracle-loop",
    name: "ORACLE LOOP",
    slot: "weapon",
    attack: 11,
    defense: 1,
    agility: 5,
    description: "A circular mnemonic conductor that answers Ione's gestures.",
    price: 0,
    allowedMembers: ["ione"],
  },
  "storm-carbine": {
    id: "storm-carbine",
    name: "STORM CARBINE",
    slot: "weapon",
    attack: 18,
    defense: 0,
    agility: 6,
    description: "An eastern marksman's weapon built to fire through electrical haze.",
    price: 0,
    allowedMembers: ["nox"],
  },
  "tower-aegis": {
    id: "tower-aegis",
    name: "TOWER AEGIS",
    slot: "shield",
    attack: 0,
    defense: 9,
    agility: 1,
    description: "A command-grade barrier projector recovered beneath the saboteur's nest.",
    price: 0,
    allowedMembers: ["ash", "ione", "nox"],
  },
  "tidebreaker-saber": {
    id: "tidebreaker-saber",
    name: "TIDEBREAKER SABER",
    slot: "weapon",
    attack: 13,
    defense: 2,
    agility: 1,
    description: "A salt-sealed saber balanced for Ash and the southern sea roads.",
    price: 1480,
    allowedMembers: ["ash"],
  },
  "mooncurrent-lash": {
    id: "mooncurrent-lash",
    name: "MOONCURRENT LASH",
    slot: "weapon",
    attack: 10,
    defense: 1,
    agility: 5,
    description: "A fluid mnemonic filament that follows Ione's smallest gesture.",
    price: 1540,
    allowedMembers: ["ione"],
  },
  "harbor-carbine": {
    id: "harbor-carbine",
    name: "HARBOR CARBINE",
    slot: "weapon",
    attack: 21,
    defense: 1,
    agility: 7,
    description: "A corrosion-proof carbine carried by Tideglass signal wardens.",
    price: 1620,
    allowedMembers: ["nox"],
  },
  "pelagic-mail": {
    id: "pelagic-mail",
    name: "PELAGIC MAIL",
    slot: "armor",
    attack: 0,
    defense: 10,
    agility: -1,
    description: "Layered shell-metal plate made for heavy impacts and salt storms.",
    price: 1360,
    allowedMembers: ["ash", "nox"],
  },
  "current-weave": {
    id: "current-weave",
    name: "CURRENT WEAVE",
    slot: "armor",
    attack: 0,
    defense: 8,
    agility: 4,
    description: "A light conductive weave that redirects force around its wearer.",
    price: 1420,
    allowedMembers: ["ione"],
  },
  "deepwater-aegis": {
    id: "deepwater-aegis",
    name: "DEEPWATER AEGIS",
    slot: "shield",
    attack: 0,
    defense: 9,
    agility: 3,
    description: "A mobile barrier tuned against pressure waves and abyssal signals.",
    price: 1680,
    allowedMembers: ["ash", "ione", "nox", "sera"],
  },
  "harbor-disc": {
    id: "harbor-disc",
    name: "HARBOR DISC",
    slot: "weapon",
    attack: 8,
    defense: 0,
    agility: 4,
    description: "Sera's balanced returning disc, tuned to sweep a whole formation.",
    price: 1180,
    allowedMembers: ["sera"],
  },
  "tidal-jacket": {
    id: "tidal-jacket",
    name: "TIDAL JACKET",
    slot: "armor",
    attack: 0,
    defense: 6,
    agility: 4,
    description: "Flexible warden armor that favors movement over heavy protection.",
    price: 1260,
    allowedMembers: ["sera"],
  },
  "undertide-ring": {
    id: "undertide-ring",
    name: "UNDERTIDE RING",
    slot: "weapon",
    attack: 12,
    defense: 0,
    agility: 6,
    description: "A recovered cave-metal ring whose split edge returns through narrow tunnels.",
    price: 0,
    allowedMembers: ["sera"],
  },
  "cavern-weave": {
    id: "cavern-weave",
    name: "CAVERN WEAVE",
    slot: "armor",
    attack: 0,
    defense: 9,
    agility: 5,
    description: "A mineral-thread field suit found beneath the central ridge.",
    price: 0,
    allowedMembers: ["sera"],
  },
  "meridian-disc": {
    id: "meridian-disc",
    name: "MERIDIAN DISC",
    slot: "weapon",
    attack: 16,
    defense: 1,
    agility: 7,
    description: "A costly precision disc calibrated in Cairn Meridian.",
    price: 2460,
    allowedMembers: ["sera"],
  },
  "meridian-guard": {
    id: "meridian-guard",
    name: "MERIDIAN GUARD",
    slot: "shield",
    attack: 0,
    defense: 11,
    agility: 3,
    description: "A light orbiting guard plate shared by southern explorers.",
    price: 2280,
    allowedMembers: ["ash", "ione", "nox", "sera"],
  },
};

export function createDefaultLoadout(memberId: PartyMemberProgress["id"]): EquipmentLoadout {
  return memberId === "sera"
    ? { weapon: "harbor-disc", armor: "tidal-jacket", shield: null, core: null }
    : memberId === "ione"
    ? { weapon: "archive-rod", armor: "woven-mantle", shield: null, core: null }
    : { weapon: "relay-blade", armor: "field-suit", shield: null, core: null };
}

export function effectiveStats(member: PartyMemberProgress): {
  attack: number;
  defense: number;
  agility: number;
} {
  const equipped = Object.values(member.equipment)
    .filter((id): id is EquipmentId => id !== null)
    .map((id) => EQUIPMENT[id]);
  return {
    attack: member.attack + equipped.reduce((total, item) => total + item.attack, 0),
    defense: member.defense + equipped.reduce((total, item) => total + item.defense, 0),
    agility: member.agility + equipped.reduce((total, item) => total + item.agility, 0),
  };
}

export function canEquip(memberId: PartyMemberId, equipmentId: EquipmentId): boolean {
  return EQUIPMENT[equipmentId].allowedMembers.includes(memberId);
}
