import type { SpellId } from "../types/game";

export interface SpellDefinition {
  id: SpellId;
  name: string;
  cost: number;
  description: string;
  target: "enemy" | "all-enemies" | "ally" | "all-allies" | "self";
  power: number;
  kind: "damage" | "heal" | "status";
  status?: "barrier" | "burn" | "shock" | "weaken" | "overclock" | "haste" | "slow";
  statusChance?: number;
  statusTurns?: number;
  defensePiercing?: number;
  visual: "arc-bolt" | "flare-lance" | "mend" | "static-field" | "barrier" | "weaken" | "shock";
}

export const SPELLS: Record<SpellId, SpellDefinition> = {
  "arc-bolt": {
    id: "arc-bolt",
    name: "ARC BOLT",
    cost: 4,
    description: "Launches a focused arc of relay energy.",
    target: "enemy",
    power: 15,
    kind: "damage",
    visual: "arc-bolt",
  },
  "guard-pulse": {
    id: "guard-pulse",
    name: "GUARD PULSE",
    cost: 5,
    description: "Halves incoming damage to one ally for two turns.",
    target: "ally",
    power: 0,
    kind: "status",
    status: "barrier",
    statusTurns: 2,
    visual: "barrier",
  },
  "flare-lance": {
    id: "flare-lance",
    name: "FLARE LANCE",
    cost: 7,
    description: "Pierces one signal with concentrated solar fire.",
    target: "enemy",
    power: 23,
    kind: "damage",
    defensePiercing: 0.25,
    visual: "flare-lance",
  },
  "solar-wave": {
    id: "solar-wave",
    name: "SOLAR WAVE",
    cost: 12,
    description: "Scorches all enemies and may leave them burning.",
    target: "all-enemies",
    power: 18,
    kind: "damage",
    status: "burn",
    statusChance: 0.65,
    statusTurns: 3,
    visual: "flare-lance",
  },
  "radiant-edge": {
    id: "radiant-edge",
    name: "RADIANT EDGE",
    cost: 13,
    description: "A concentrated blade of light that pierces one enemy.",
    target: "enemy",
    power: 31,
    kind: "damage",
    defensePiercing: 0.35,
    visual: "flare-lance",
  },
  "aurora-guard": {
    id: "aurora-guard",
    name: "AURORA GUARD",
    cost: 14,
    description: "Wraps Ash in a four-turn defensive barrier.",
    target: "self",
    power: 0,
    kind: "status",
    status: "barrier",
    statusTurns: 4,
    visual: "barrier",
  },
  "nova-drive": {
    id: "nova-drive",
    name: "NOVA DRIVE",
    cost: 22,
    description: "Drives solar fire through the entire enemy formation.",
    target: "all-enemies",
    power: 28,
    kind: "damage",
    status: "burn",
    statusChance: 0.75,
    statusTurns: 3,
    visual: "flare-lance",
  },
  mend: {
    id: "mend",
    name: "MEND",
    cost: 5,
    description: "Restores one chosen ally's HP.",
    target: "ally",
    power: 12,
    kind: "heal",
    visual: "mend",
  },
  "static-field": {
    id: "static-field",
    name: "STATIC FIELD",
    cost: 6,
    description: "Discharges archive current through every enemy.",
    target: "all-enemies",
    power: 10,
    kind: "damage",
    status: "shock",
    statusChance: 0.3,
    statusTurns: 2,
    visual: "static-field",
  },
  "signal-break": {
    id: "signal-break",
    name: "SIGNAL BREAK",
    cost: 6,
    description: "Weakens one enemy's attack for three turns.",
    target: "enemy",
    power: 0,
    kind: "status",
    status: "weaken",
    statusTurns: 3,
    visual: "weaken",
  },
  "renewal-wave": {
    id: "renewal-wave",
    name: "RENEWAL WAVE",
    cost: 11,
    description: "Restores HP to every living ally.",
    target: "all-allies",
    power: 15,
    kind: "heal",
    visual: "mend",
  },
  "aegis-veil": {
    id: "aegis-veil",
    name: "AEGIS VEIL",
    cost: 14,
    description: "Protects the entire party with a two-turn barrier.",
    target: "all-allies",
    power: 0,
    kind: "status",
    status: "barrier",
    statusTurns: 2,
    visual: "barrier",
  },
  "deep-mend": {
    id: "deep-mend",
    name: "DEEP MEND",
    cost: 12,
    description: "Restores a large amount of HP to one living ally.",
    target: "ally",
    power: 34,
    kind: "heal",
    visual: "mend",
  },
  "archive-storm": {
    id: "archive-storm",
    name: "ARCHIVE STORM",
    cost: 18,
    description: "Strikes all enemies with memory lightning and may shock them.",
    target: "all-enemies",
    power: 23,
    kind: "damage",
    status: "shock",
    statusChance: 0.45,
    statusTurns: 2,
    visual: "static-field",
  },
  "restoration-wave": {
    id: "restoration-wave",
    name: "RESTORE WAVE",
    cost: 24,
    description: "Restores heavy HP to every living ally.",
    target: "all-allies",
    power: 36,
    kind: "heal",
    visual: "mend",
  },
  "pulse-round": {
    id: "pulse-round",
    name: "PULSE ROUND",
    cost: 3,
    description: "A precise shot that ignores part of the target's armor.",
    target: "enemy",
    power: 13,
    kind: "damage",
    defensePiercing: 0.45,
    visual: "arc-bolt",
  },
  "shock-round": {
    id: "shock-round",
    name: "SHOCK ROUND",
    cost: 5,
    description: "A charged shot that may interrupt enemy actions.",
    target: "enemy",
    power: 15,
    kind: "damage",
    status: "shock",
    statusChance: 0.65,
    statusTurns: 2,
    visual: "shock",
  },
  scattershot: {
    id: "scattershot",
    name: "SCATTERSHOT",
    cost: 8,
    description: "Sprays pulse fire across the enemy formation.",
    target: "all-enemies",
    power: 12,
    kind: "damage",
    defensePiercing: 0.25,
    visual: "static-field",
  },
  "armor-piercer": {
    id: "armor-piercer",
    name: "ARMOR PIERCER",
    cost: 9,
    description: "A high-impact round that almost ignores defense.",
    target: "enemy",
    power: 24,
    kind: "damage",
    defensePiercing: 0.8,
    visual: "flare-lance",
  },
  overclock: {
    id: "overclock",
    name: "OVERCLOCK",
    cost: 10,
    description: "Raises Nox's attack and agility for three turns.",
    target: "self",
    power: 0,
    kind: "status",
    status: "overclock",
    statusTurns: 3,
    visual: "barrier",
  },
  "breach-burst": {
    id: "breach-burst",
    name: "BREACH BURST",
    cost: 13,
    description: "Sweeps the formation with armor-breaking pulse fire.",
    target: "all-enemies",
    power: 19,
    kind: "damage",
    defensePiercing: 0.55,
    visual: "static-field",
  },
  "rail-shot": {
    id: "rail-shot",
    name: "RAIL SHOT",
    cost: 16,
    description: "A massive single shot that almost entirely ignores defense.",
    target: "enemy",
    power: 39,
    kind: "damage",
    defensePiercing: 0.9,
    visual: "flare-lance",
  },
  "zero-volley": {
    id: "zero-volley",
    name: "ZERO VOLLEY",
    cost: 23,
    description: "Bombards every enemy with piercing, disruptive fire.",
    target: "all-enemies",
    power: 28,
    kind: "damage",
    status: "shock",
    statusChance: 0.4,
    statusTurns: 2,
    defensePiercing: 0.5,
    visual: "shock",
  },
  "quick-current": {
    id: "quick-current",
    name: "QUICK CURRENT",
    cost: 7,
    description: "Raises every ally's agility for three turns.",
    target: "all-allies",
    power: 0,
    kind: "status",
    status: "haste",
    statusTurns: 3,
    visual: "barrier",
  },
  "undertow-hex": {
    id: "undertow-hex",
    name: "UNDERTOW HEX",
    cost: 6,
    description: "Slows one enemy's actions for three turns.",
    target: "enemy",
    power: 0,
    kind: "status",
    status: "slow",
    statusTurns: 3,
    visual: "weaken",
  },
  "pressure-veil": {
    id: "pressure-veil",
    name: "PRESSURE VEIL",
    cost: 9,
    description: "Weakens every enemy's attack for three turns.",
    target: "all-enemies",
    power: 0,
    kind: "status",
    status: "weaken",
    statusTurns: 3,
    visual: "weaken",
  },
  "mending-tide": {
    id: "mending-tide",
    name: "MENDING TIDE",
    cost: 12,
    description: "Restores modest HP to every living ally.",
    target: "all-allies",
    power: 10,
    kind: "heal",
    visual: "mend",
  },
  "stillwater-field": {
    id: "stillwater-field",
    name: "STILLWATER",
    cost: 14,
    description: "Slows every enemy for two turns.",
    target: "all-enemies",
    power: 0,
    kind: "status",
    status: "slow",
    statusTurns: 2,
    visual: "weaken",
  },
  "tidal-aegis": {
    id: "tidal-aegis",
    name: "TIDAL AEGIS",
    cost: 17,
    description: "Protects the entire party for three turns.",
    target: "all-allies",
    power: 0,
    kind: "status",
    status: "barrier",
    statusTurns: 3,
    visual: "barrier",
  },
  "low-tide": {
    id: "low-tide",
    name: "LOW TIDE",
    cost: 18,
    description: "Damages the formation and may weaken every enemy.",
    target: "all-enemies",
    power: 18,
    kind: "damage",
    status: "weaken",
    statusChance: 0.7,
    statusTurns: 3,
    visual: "weaken",
  },
  "horizon-current": {
    id: "horizon-current",
    name: "HORIZON CURRENT",
    cost: 24,
    description: "Restores the party with a wide but gentle healing current.",
    target: "all-allies",
    power: 24,
    kind: "heal",
    visual: "mend",
  },
};
